### ISSUE TITLE
My application stopped receiving requests in open sea

### ISSUE THREAD

**Issue by LG95** [ZupIT/charlescd#819]
**Describe the bug**
I have two applications, a Spring based Beagle BFF and a simple Spring CRUD micro service, deployed in open sea and another circle. They were working normally, until yesterday the BFF started responding HTTP 404 with no body, but both normally respond Spring's 404 HTML for non existent endpoints. The micro service is responding normally in open sea. 
I looked inside my cluster and found that the BFF responded normally when I port forwarded the pod and the service, but a pod inside the namespace got the same 404 response when it `curl`ed the BFF. Through these `curl` tests, I was only able to receive a response when I specified my other circle's id in the `x-circle-id` header.  I have an nginx load balancing for the namespace and it is exposed as https://beagle.continuousplatform.com. The BFF is available under [/tmdb/bff](https://beagle.continuousplatform.com/tmdb/bff) and the micro service under [/tmdb/account](https://beagle.continuousplatform.com/tmdb/account).

**To Reproduce**
Since my application was working on one day and on the other stopped without us doing anything in our cluster or in Charles, I do not know how to reproduce the error. However, the broken pod is still present in our cluster, please contact me and we can analyze it together.

**Expected behavior**
My application continued operating normally.

**Your Environment**
- CharlesCD version used: https://charles-prod.continuousplatform.com/
- Description of environment where CharlesCD is running: beagle-cluster in Beagle's production AWS cloud
- Browser Name and version (if applicable): N/A

**Comment by emiteze** [comment]
We had a breaking change on butler's architecture when we implemented the second version that solved many problems that we had to deal with in our first version, and then we noticed that old deployments made in the first version would not be compatible with new deployments in the second version, so this problem ocurred cause the stable deployment that you had on open sea was made by our first butler version, and then a new deployment was made using the second version of butler, and this kind of "bugged" the destination rules and virtualservices that the second version applied to this component. Redeploying the stable version using butler v2 solved the problem and we will now watch closely to see if this don't happen anymore, since now you will be using the butler v2 =)

**Comment by LG95** [comment]
Thanks!
